name: pro_design
description: A Flutter package to develop responsive flutter applications easily in different ways. Try this and make your widgets and fonts responsive on any screen size.
version: 0.0.5
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
